version: '3.8'
services:

  riot-proxy-api:
    build:
      context: .
      dockerfile: apps/riot-proxy/Dockerfile
    ports:
      - '3001:3001'
    environment:
      RIOT_API_KEY: ${RIOT_API_KEY}

  postgres:
    image: postgres:14.5-alpine3.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  user:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    ports:
      - '3002:3002'
    environment:
      RIOT_PROXY_BASE_PATH: http://riot-proxy-api:3001
      DATABASE_HOST: postgres

  report:
    build:
      context: .
      dockerfile: apps/report/Dockerfile
    ports:
      - '3003:3003'
    environment:
      RIOT_PROXY_BASE_PATH: http://riot-proxy-api:3001
      USER_BASE_PATH: http://user:3002

  discord-bot:
    build:
      context: .
      dockerfile: apps/discord-bot/Dockerfile
    ports:
      - '3004:3004'
    environment:
      USER_BASE_PATH: http://user:3002
      REPORT_BASE_PATH: http://report:3003
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}

volumes:
  db:
    driver: local
